#!/bin/sh

vim -p compiler/pngtosprite compiler/voxeltosprite compiler/pngtolevel compiler/pzr
vim -p src/dungeon.predude texts/prelude.txt texts/objects.txt texts/legend.txt texts/layers.txt texts/rules.txt texts/levels.txt
vim -p pausewhenstationary.png setuplevel.rule
