#!/usr/bin/env python3

import os
import sys
from PIL import Image

#construct dict of chars to colors
legend_dict = {}
legend_file = "../texts/legend.txt"
with open(legend_file) as f:
  legend_lines = f.read().splitlines()
for line in legend_lines:
  line_list = line.strip().split(" ")
  color = line_list[-1].lstrip("(").rstrip(")")
  legend_dict[color.lower()] = line_list[0]

#print the level
level_file = "../levels/"+sys.argv[1]
im = Image.open(level_file).convert('RGBA')
pix = im.load()
line = ""
for j in range(im.size[1]):
  line = ""
  for i in range(im.size[0]):
    r, g, b, a = pix[i, j]
    curPixel = curPixel = '#%02x%02x%02x' % (r, g, b)
    if (a == 0):
      line += "."
      continue
    line += legend_dict[curPixel.lower()]       
  print (line)
print("")

