#!/usr/bin/env python3

def addUnique(l,item):
  if item not in l:
    l.append(item)
  return l

from PIL import Image
import sys

#setuppixels
im = Image.open(sys.argv[1]).convert('RGBA')
pix = im.load()

#createcolorset
out_l_l = [[0 for x in range(im.size[0])] for x in range(im.size[1])] 
col_set = []
for j in range(im.size[1]):
  for i in range(im.size[0]):
    r, g, b, a = pix[i,j]
    curPixel = '#%02x%02x%02x' % (r, g, b)
    if a != 0:
      addUnique(col_set, curPixel)
col_set.sort()

#printcolorset
line = ""
for item in col_set:
  line += item + " "
print (line)

#print sprite (object)
for j in range (im.size[1]):
  line = ""
  for i in range (im.size[0]):
    r,g,b,a = pix[i,j]
    if (a == 0):
      line += "."
    else:
      curPixel = '#%02x%02x%02x' % (r, g, b)
      line += str(col_set.index(curPixel))
  print(line)
