#!/usr/bin/env python3

voxel_dir = "../voxels/"
 
def addUnique(l,item):
  if item not in l:
    l.append(item)
  return l

def atoi(text):
  return int(text) if text.isdigit() else text

def natural_keys(text):
  return [ atoi(c) for c in re.split('(\d+)', text) ]

from PIL import Image
import sys
import os
import re

#findthepad?
pad_top = False
if (len(sys.argv) > 2):
  pad_top = True
  top_pad = int(sys.argv[2])

#getpngsfromfilesystem
voxel_dir = voxel_dir+sys.argv[1]
voxel_files = []
voxel_list = os.listdir(voxel_dir)
voxel_list.sort(key=natural_keys)
for f in voxel_list:
  if f.endswith(".png"):
    voxel_files.append(os.path.join(voxel_dir,f))
    
#parseimagetofindcollectivecolorset
col_set = []
for f in voxel_files:
  im = Image.open(f).convert('RGBA')
  pix = im.load()
  out_l_l = [[0 for x in range(im.size[0])] for x in range(im.size[1])] 
  for j in range(im.size[1]):
    for i in range(im.size[0]):
      r, g, b, a = pix[i,j]
      curPixel = '#%02x%02x%02x' % (r, g, b)
      if a != 0:
        addUnique(col_set, curPixel)
col_set.sort()

# printcolorset
line = ""
for item in col_set:
  line += item + " "
print (line)

#setuppixels
im = Image.open(voxel_files[0]).convert('RGBA')
pix = im.load()

#printtoppaddingifany
if pad_top:
  for i in range(top_pad-1):
    print(".\n&")
  print(".\n&")
  
#printindex0
for j in range (im.size[1]):
  line = ""
  for i in range (im.size[0]):
    r,g,b,a = pix[i,j]
    if (a == 0):
      line += "."
    else:
      curPixel = '#%02x%02x%02x' % (r, g, b)
      line += str(col_set.index(curPixel))
  print(line)

#printindex1-n
for f in voxel_files[1:]:
  print("&")
  im = Image.open(f).convert('RGBA')
  pix = im.load()
  for j in range (im.size[1]):
    line = ""
    for i in range (im.size[0]):
      r,g,b,a = pix[i,j]
      if (a == 0):
        line += "."
      else:
        curPixel = '#%02x%02x%02x' % (r, g, b)
        line += str(col_set.index(curPixel))
    print(line)
