#!/usr/bin/env python3

from pzr_utils import *

pix, w, h = pixels_w_h(sys.argv[1])

#createcolorset
out_l_l = [[0 for x in range(w)] for x in range(h)] 
col_set = []
for j in range(h):
  for i in range(w):
    r, g, b, a, hcolor = rgbah(pix,i,j) 
    if a != 0:
      addUnique(col_set, hcolor)
col_set.sort()

#printcolorset
line = ""
for item in col_set:
  line += item + " "
print (line)

#print sprite (object)
for j in range (h):
  line = ""
  for i in range (w):
    r, g, b, a, hcolor = rgbah(pix,i,j)
    if (a == 0):
      line += "."
    else:
      line += str(col_set.index(hcolor))
  print(line)
