#!/usr/bin/env python3

def addUnique(l,item):
  if item not in l:
    l.append(item)
  return l

from PIL import Image
import sys

image_path = sys.argv[1]
#setuppixels
im = Image.open(image_path).convert('RGBA')
pix = im.load()
w = im.size[0]
h = im.size[1]

#createcolorset
out_l_l = [[0 for x in range(w)] for x in range(h)] 
col_set = []
for j in range(h):
  for i in range(w):
    r, g, b, a = pix[i,j]
    curPixel = '#%02x%02x%02x' % (r, g, b)
    if a != 0:
      addUnique(col_set, curPixel)
col_set.sort()

#printcolorset
line = ""
for item in col_set:
  line += item + " "
print (line)

#print sprite (object)
for j in range (h):
  line = ""
  for i in range (w):
    r,g,b,a = pix[i,j]
    if (a == 0):
      line += "."
    else:
      curPixel = '#%02x%02x%02x' % (r, g, b)
      line += str(col_set.index(curPixel))
  print(line)
