#!/usr/bin/env python3
from pzr_utils import *

#construct dict of chars to colors
legend_dict = {}
legend_lines = file_to_lines(legend_file)
for line in legend_lines:
  line_list = line.strip().split(" ")
  color = line_list[-1].lstrip("(").rstrip(")")
  legend_dict[color.lower()] = line_list[0]

#print the level
level_file = "../levels/"+sys.argv[1]
pix, w, h = pixels_w_h(level_file)
line = ""
for j in range(h):
  line = ""
  for i in range(w):
    r, g, b, a = pix[i, j]
    curPixel = curPixel = '#%02x%02x%02x' % (r, g, b)
    if (a == 0):
      line += "."
      continue
    line += legend_dict[curPixel.lower()]       
  print (line)
