#!/usr/bin/env python3

from pzr_utils import *

#pass0
lines = file_to_lines(src_dir+game_file)

#pass1
tlines = []
for line in lines:
  if (".txt" in line):
    text_file = line.strip()
    text_lines = file_to_lines(text_dir+text_file)
    tlines.extend(text_lines) 
  elif (".object" in line):
    object_files = files_in_folder(".o",objects_dir)
    for f in object_files:
      tlines.append("")
      o_lines = file_to_lines(f)
      tlines.extend(o_lines)
      tlines.append("")
  else:
    tlines.append(line)
lines = tlines
      
#pass2
out = []
for line in lines:
  if (".level" in line):
    level_file = line.strip().split(".")[0]+".png"
    level_lines = os.popen("./pngtolevel {}".format(level_file)).read().split('\n')
    out.extend(level_lines)
  elif (".png" in line):
    sprite_file = line.strip()
    sprite_lines = os.popen("./pngtosprite {}".format(image_dir+sprite_file)).read().split('\n')
    out.extend(sprite_lines)
  elif (".rule" in line):
    rules_file = line.strip()
    rules_lines = file_to_lines(rules_dir+rules_file)
    out.extend(rules_lines)
  elif (".voxel" in line):
    # get list of all files in the directory
    voxel_list = line.strip().split(" ") # how many args
    pad_top = False
    pad_bottom = False
    if (len(voxel_list) == 2):
      pad_top = True
    elif (len(voxel_list) == 3):
      pad_bottom = True
    if (pad_top):
      voxel_file = voxel_list[0]
      voxel_basename = voxel_file.split(".")[0] 
      pad_arg = voxel_list[1]
      voxel_lines = os.popen("./voxeltosprite {} {}".format(voxel_basename,pad_arg)).read().split('\n')
      out.extend(voxel_lines)
    elif (pad_bottom):
      voxel_file = voxel_list[0]
      voxel_basename = voxel_file.split(".")[0] 
      top_pad_arg = voxel_list[1]
      bottom_pad_arg = voxel_list[2]
      voxel_lines = os.popen("./voxeltosprite {} {} {}".format(voxel_basename,top_pad_arg, bottom_pad_arg)).read().split('\n')
      out.extend(voxel_lines)
    else:
      voxel_file = line.strip()
      voxel_basename = line.split(".")[0]
      voxel_lines = os.popen("./voxeltosprite {}".format(voxel_basename)).read().split('\n')
      out.extend(voxel_lines)
  else:
    out.append(line)

#prepareandsave
write_list_to_file(out,out_dir+game_file)

#insertintoclipboardtoo!
os.system("cat {} | pbcopy".format(out_dir+game_file))
