#!/usr/bin/env python3
from pzr_utils import *

#findthepad?
pad_top = False
pad_bottom = False
top_pad = 0
bottom_pad = 0
if (len(sys.argv) == 3):
  pad_top = True
  top_pad = int(sys.argv[2])
elif (len(sys.argv) == 4):
  pad_top= True
  top_pad = int(sys.argv[2])
  pad_bottom = True
  bottom_pad = int(sys.argv[3])

#getpngsfromfilesystem
voxel_dir = voxel_dir+sys.argv[1]
voxel_files = []
voxel_list = os.listdir(voxel_dir)
voxel_list.sort(key=natural_keys)
for f in voxel_list:
  if f.endswith(".png"):
    voxel_files.append(os.path.join(voxel_dir,f))
    
#parseimagetofindcollectivecolorset
col_set = []
for f in voxel_files:
  pix, w, h = pixels_w_h(f)
  out_l_l = [[0 for x in range(w)] for x in range(h)] 
  for j in range(h):
    for i in range(w):
      r, g, b, a, hcolor = rgbah(pix,i,j)
      if a != 0:
        addUnique(col_set, hcolor)
col_set.sort()

# printcolorset
line = ""
for item in col_set:
  line += item + " "
print (line)

#printtoppaddingifany
if pad_top and top_pad != 0:
  for i in range(top_pad-1):
    print(".")
    print("&")
  print(".\n&")
  
#printindex0
pix, w, h = pixels_w_h(voxel_files[0])
for j in range (h):
  line = ""
  for i in range (w):
    r, g, b, a, hcolor = rgbah(pix,i,j)
    if (a == 0):
      line += "."
    else:
      line += str(col_set.index(hcolor))
  print(line)

#printindex1-n
for f in voxel_files[1:]:
  print("&")
  pix, w, h = pixels_w_h(f)
  for j in range (h):
    line = ""
    for i in range (w):
      r, g, b, a, hcolor = rgbah(pix,i,j)
      if (a == 0):
        line += "."
      else:
        line += str(col_set.index(hcolor))
    print(line)

#printbottompadding
if pad_bottom and bottom_pad != 0:
  for i in range(bottom_pad-1):
    print("&")
    print(".")
