#!/usr/bin/env python3
from pzr_utils import *

#findthepad?
pad_top = False
pad_bottom = False
top_pad = 0
bottom_pad = 0
if (len(sys.argv) == 3):
  pad_top = True
  top_pad = int(sys.argv[2])
elif (len(sys.argv) == 4):
  pad_top= True
  top_pad = int(sys.argv[2])
  pad_bottom = True
  bottom_pad = int(sys.argv[3])

#getpngsfromfilesystem
voxel_dir = voxel_dir+sys.argv[1]
voxel_files = sorted_files_in_folder(".png",voxel_dir)
    
#parseimagetofindcollectivecolorset XXX has to be done in case top voxel doesnt contain all the colors ;)
col_set= []
for f in voxel_files:
  pix, w, h, cur_col_set = pixels_whc(f)
  for c in cur_col_set:
    addUnique(col_set,c)

# printcolorset
print_hcolor_list(col_set)

#printtoppaddingifany
if pad_top and top_pad != 0:
  for i in range(top_pad-1):
    print(".")
    print("&")
  print(".\n&")
  
#printindex0
pix, w, h = pixels_w_h(voxel_files[0])
for j in range (h):
  line = ""
  for i in range (w):
    r, g, b, a, hcolor = rgbah(pix,i,j)
    if (a == 0):
      line += "."
    else:
      line += str(col_set.index(hcolor))
  print(line)

#printindex1-n
for f in voxel_files[1:]:
  print("&")
  pix, w, h = pixels_w_h(f)
  for j in range (h):
    line = ""
    for i in range (w):
      r, g, b, a, hcolor = rgbah(pix,i,j)
      if (a == 0):
        line += "."
      else:
        line += str(col_set.index(hcolor))
    print(line)

#printbottompadding
if pad_bottom and bottom_pad != 0:
  for i in range(bottom_pad-1):
    print("&")
    print(".")
