#!/usr/bin/env python3

voxel_dir = "../voxels/"
 
def addUnique(l,item):
  if item not in l:
    l.append(item)
  return l

def atoi(text):
  return int(text) if text.isdigit() else text

#withoutthis,thisscriptfails
def natural_keys(text):
  return [ atoi(c) for c in re.split('(\d+)', text) ]

from PIL import Image
import sys
import os
import re

#findthepad?
pad_top = False
pad_bottom = False
top_pad = 0
bottom_pad = 0
if (len(sys.argv) == 3):
  pad_top = True
  top_pad = int(sys.argv[2])
elif (len(sys.argv) == 4):
  pad_top= True
  top_pad = int(sys.argv[2])
  pad_bottom = True
  bottom_pad = int(sys.argv[3])

#getpngsfromfilesystem
voxel_dir = voxel_dir+sys.argv[1]
voxel_files = []
voxel_list = os.listdir(voxel_dir)
voxel_list.sort(key=natural_keys)
for f in voxel_list:
  if f.endswith(".png"):
    voxel_files.append(os.path.join(voxel_dir,f))
    
#parseimagetofindcollectivecolorset
col_set = []
for f in voxel_files:
  im = Image.open(f).convert('RGBA')
  pix = im.load()
  w = im.size[0]
  h = im.size[1]
  out_l_l = [[0 for x in range(w)] for x in range(h)] 
  for j in range(h):
    for i in range(w):
      r, g, b, a = pix[i,j]
      curPixel = '#%02x%02x%02x' % (r, g, b)
      if a != 0:
        addUnique(col_set, curPixel)
col_set.sort()

# printcolorset
line = ""
for item in col_set:
  line += item + " "
print (line)

#setuppixels
im = Image.open(voxel_files[0]).convert('RGBA')
pix = im.load()
w = im.size[0]
h = im.size[1]

#printtoppaddingifany
if pad_top and top_pad != 0:
  for i in range(top_pad-1):
    print(".")
    print("&")
  print(".\n&")
  
#printindex0
for j in range (h):
  line = ""
  for i in range (w):
    r,g,b,a = pix[i,j]
    if (a == 0):
      line += "."
    else:
      curPixel = '#%02x%02x%02x' % (r, g, b)
      line += str(col_set.index(curPixel))
  print(line)

#printindex1-n
for f in voxel_files[1:]:
  print("&")
  im = Image.open(f).convert('RGBA')
  pix = im.load()
  w = im.size[0]
  h = im.size[1]
  for j in range (h):
    line = ""
    for i in range (w):
      r,g,b,a = pix[i,j]
      if (a == 0):
        line += "."
      else:
        curPixel = '#%02x%02x%02x' % (r, g, b)
        line += str(col_set.index(curPixel))
    print(line)

#printbottompadding
if pad_bottom and bottom_pad != 0:
  for i in range(bottom_pad-1):
    print("&")
    print(".")
